### ISSUE TITLE
additional features for ground image viewer

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#12]
- show the file size of the downlinked file (so that the user knows if a lower quality or scaling is preferable)
- probably can drop the focal length display
- make the font size smaller to make better use of screen real estate
- avoid ellipsis for timestamps
- maybe try two column layout along left edge?

**Comment by ckjellstrand** [comment]
I like the focal length display - I occasionally forget if I am looking at a 50mm or 135mm picture and we might as well if we are switching between images from different cameras. I could also add a camera_id instead, though.
