### ISSUE TITLE
decode aperture_stop and lens_status in GUI

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#16]
use new functions in 
https://github.com/PolarMesosphericClouds/PMC-Turbo/blob/master/pmc_turbo/camera/pycamera/dtypes.py#L28
to decode the values of aperture_stop and lens_status

**Comment by ckjellstrand** [comment]
Closed by a9c577fe8f2a6cac9df68793fbd86dfdd688ebaf
