### ISSUE TITLE
Reorganize pgcamera code

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#24]
For maintainability and ease of changes I suggest the following:

Extract the custom widgets which are in the infobar into proper widgets (right now they're all initialized in InfoBar.__init__.
So for example, instead of 
<pre>
        time_widget = QtGui.QWidget()
        time_layout = QtGui.QGridLayout()
        time_widget.setLayout(time_layout)
        time_layout.addWidget(frame_timestamp_s, 2, 0)
</pre>

do
<pre>
class TimeWidget(QWidget):
    def __init__(...):
        self.layout = QGridLayout()
        self.labels = ...
        self.layout.addWidget(...)
....
</pre>

and then in InfoBar.__init__ just instantiate a TimeWidget and add it to the InfoBar layout.

It would also be cleaner to make something like an ItemWidget that encapsulates the label and value fields. You could then subclass it for items that need special formatting for the value etc.

**Comment by ckjellstrand** [comment]
Closed by 6114308cee0d78b116a643ab9df15f372a9ce26e
