### ISSUE TITLE
missing disk on pmc-camera-2

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#27]
pmc-camera-2 has these disks
<pre>
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0USS7Y -> ../../sdc
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0UWTEY -> ../../sdd
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0U206Y -> ../../sda
</pre>
but fstab shows these entries:
<pre>
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0UEKSY-part3 /data1 ext4 nofail 0 2
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0U206Y-part3 /data2 ext4 nofail 0 2
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0USS7Y-part1 /data3 ext4 nofail 0 2
/dev/disk/by-id/ata-WDC_WD80EFZX-68UW8N0_VK0UWTEY-part1 /data4 ext4 nofail 0 2
</pre>

The data1 disk VK0UEKSY seems to be missing.

**Comment by gitj** [comment]
Appears that SATA cable was strung too tightly and loosened from motherboard connection

**Comment by gitj** [comment]
/data1 (serial number VK0UEKSY) is missing again. Need to check if cable needs to be replaced.

**Comment by ckjellstrand** [comment]
The cable is completely unplugged.

**Comment by ckjellstrand** [comment]
Cable was plugged in. Since then the OS has been completely re-installed and disks reformatted multiple times.
