### ISSUE TITLE
add testing for housekeeping classes

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#34]
clean up code (remove unused features)
https://codecov.io/gh/PolarMesosphericClouds/PMC-Turbo/src/master/pmc_turbo/communication/housekeeping_classes.py

**Comment by ckjellstrand** [comment]
Removed unused code and added running through code for coverage.

Closed by 49362d150051d6e9cdbfcad0a720e260e23ec98d (and previous 3 commits).
