### ISSUE TITLE
finish lowrate monitor gui improvements

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#41]
add colors and value formatting for new table based gui to make it as informative as original

**Comment by ckjellstrand** [comment]
- Make short_status_format or short_status_ranges.py which contains OrderedDict of (item name from short status, human readable item name, formatting (e.g. %.2f), good range, bad range)
 - Write a function to take in an item name from short status, and output the human readable name, and a value which is correctly formatted and ready for input into the table of lowrate_monitor_gui
 - Make lowrate_monitor_gui highlight columns (background color) which are new, old, etc.

**Comment by ckjellstrand** [comment]
Formatting needs to be more than just string formatting - needs to be a function (for example, to divide value by 1000 to get easily readable units)

**Comment by ckjellstrand** [comment]
Most of this is closed. Need to find good names and formatting for several items.
