### ISSUE TITLE
pmc-camera-7 doesn't hear commands on openport

### ISSUE THREAD

**Issue by ckjellstrand** [PolarMesosphericClouds/PMC-Turbo#61]
I sent several commands - set_leader, set_peer_polling_order, set_downlink_bandwidth. pmc-camera-7 did not see the commands unless I set_link_tdrss.

**Comment by ckjellstrand** [comment]
The commands never registered at recvd in command log monitor.

**Comment by gitj** [comment]
This is expected: the router is only configured to forward commands to pmc-camera-6 currently. need to add forwarding for other systems
