### ISSUE TITLE
Prominent label for which camera is associated with a pgcamera instance.

### ISSUE THREAD

**Issue by ckjellstrand** [PolarMesosphericClouds/PMC-Turbo#70]

**Comment by ckjellstrand** [comment]
Closed by 956ceb4d4e2689f948eb227c90d1cade08e89f72

**Comment by gitj** [comment]
The label just shows the camera that the script was started with. Ideally it should show the camera that the current image came from (so that in all cameras mode it shows which camera the current image came from)

**Comment by ckjellstrand** [comment]
Fixed in bbcfb4078a3b620b91418150bc0f7148bc10725c
