### ISSUE TITLE
pmc_viewer add command bar back to compact view

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#81]
command bar always needs to be available.
to make it fit, make it so that the text can wrap

**Comment by gitj** [comment]
current solution doesn't work well because the extra line break gets copied.
try letting Qt just wrap the line for you, maybe need to use a LineEdit instead of a Label or something

**Comment by ckjellstrand** [comment]
Closed by 907c565620ed64347b1d192f47df7dac9d541d89
